# Example secrets file for Streamlit

# Put your OpenAI API key here
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"

[openai]
MODEL_TRANSCRIBE = "gpt-4o-transcribe"
MODEL_ANALYSIS   = "gpt-4.1"

[db]
# Example database credentials
host = "your-db-host.example.com"
user = "your_db_username"
password = "your_db_password"
database = "asterisk"

# --- Example multi-DB configuration ---
[dbs.vicidial_primary]
host = "your-db-host.example.com"
database = "asterisk"
user = "your_db_username"
password = "your_db_password"

[dbs.vicidial_alt]
host = "your-other-db-host.example.com"
database = "asterisk"
user = "your_other_db_username"
password = "your_other_db_password"
